language: python
dist: trusty
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
script:
    - make check
    - make style
install:
    - travis_retry pip install -U pip coverage codecov flake8
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libsvn-dev
